---
abstract: 'The great new Acme::GRYLLIDA::Utils! A test module.'
author:
  - 'Gryllida <Gryllida@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-GRYLLIDA-Utils
provides:
  Acme::GRYLLIDA::Utils:
    file: lib/Acme/GRYLLIDA/Utils.pm
    version: 0.01
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
